standalone_tags:
  [
    {
      id: 27,
      size: 0.2286,
      name: "miami_distal"
    }
  ]

tag_bundles:
  [
    {
      name: 'miami_portal',
      layout:
        [
          {
            id: 24,
            size: 0.2286,
            x: -1.061,
            y: -0.630,
            z: -0.165,
            qw: 0,
            qx: 1,
            qy: 0,
            qz: 0
          },
          {
            id: 25,
            size: 0.2286,
            x: -0.246,
            y: -2.316,
            z: -0.189,
            qw: 0,
            qx: 1,
            qy: 0,
            qz: 0
          },
          {
            id: 26,
            size: 0.2286,
            x:  1.074,
            y: -1.131,
            z: -0.178,
            qw: 0,
            qx: 1,
            qy: 0,
            qz: 0
          }
        ]
    }
  ]
