standalone_tags:
  [
    {
      id: 7,
      size: 0.2286,
      name: "army_distal"
    },
    {
      name: "test",
      id: 2,
      size: 0.3048,
      x: 0,
      y: 0,
      z: 0,
      qw: 0,
      qx: 1,
      qy: 0,
      qz: 0
    }
  ]

tag_bundles:
  [
    {
      name: 'army_portal',
      layout:
        [
          {
            id: 4,
            size: 0.2286,
            x: -1.067,
            y: -0.600,
            z: 0,
            qw: 0,
            qx: 1,
            qy: 0,
            qz: 0
          },
          {
            id: 5,
            size: 0.2286,
            x: -0.250,
            y: -2.286,
            z: 0,
            qw: 0,
            qx: 1,
            qy: 0,
            qz: 0
          },
          {
            id: 6,
            size: 0.2286,
            x: 1.067,
            y: -1.100,
            z: 0,
            qw: 0,
            qx: 1,
            qy: 0,
            qz: 0
          }
        ]
    }
  ]
